### ISSUE TITLE
Algorithm doesn't work .-.

### ISSUE THREAD

**Issue by LeaX-XIV** [CapraTheBest/Android-RSA-TestApp#1]
For some strange reason, it seems the encyfer algorithm doesn't want to do what it's done for.
It creates the public key correctly, but the private doesn't come up right.

**Comment by CapraTheBest** [comment]
the inversemod function is in the right place, but the values are incorrect. We need to understand which are the right values, since we don't want to have an app that use an asymmetric encryption to act as a symmetric one. Would you?

**Comment by LeaX-XIV** [comment]
You're absolutely right, mate.

**Comment by LeaX-XIV** [comment]
I just came to the conclusion we need a pro.

**Comment by LeaX-XIV** [comment]
Ok, we didn't need a pro, I just had to apply a little more.
The bug flew, the app works. What more?

**Comment by CapraTheBest** [comment]
a function that makes cappuccino

**Comment by LeaX-XIV** [comment]
I don't think it's possible to realize it with the technology we have nowadays, don't you think?

**Comment by CapraTheBest** [comment]
Necroposting is a bad thing btw

**Comment by LeaX-XIV** [comment]
Who cares

**Comment by CapraTheBest** [comment]
I do

Il 22 apr 2017 3:52 PM, "Alessandro Borione" <notifications@github.com> ha
scritto:
